import sizes from './sizes'
import bg3 from './bg3.svg'
export default
{
    "@global":
    {
        ".fade-exit":
        {
            opacity:1
        },
        ".fade-exit-active":
        {
            opacity:0,
            transition:"opacity 0.5s ease-out"
        }

    },
    root:
    {
        overflowX:'hidden',
        height:'100vh',
        display:"flex",
        alignItems:"flex-start",
        justifyContent:"center",
        backgroundColor:"#000933",
        backgroundImage:`url(${bg3})`,
        [sizes.down('sm')]:
        {
            height:'97vh',
            marginLeft:'-6.5vw',
            paddingBottom:'50px',
        },
    },
    container:
    {
        width:"50%",
        display:"flex",
        alignItems:"flex-start",
        flexDirection:"coloumn",
        flexWrap:"wrap",
        [sizes.down('lg')]:
        {
            width:"70%",
        },
        [sizes.down('md')]:
        {
            width:"80%",
        },
        [sizes.down('sm')]:
        {
            width:"80%",
            paddingBottom:"20px"
        }
    },
    nav:
    {
        display:"flex",
        justifyContent:"space-between",
        width:"100%",
        color:"#fff",
        alignItems:"center",
        "& a":
        {
            color:"#fff",
            fontSize:"1.2rem",
            marginRight:'1rem',
            [sizes.down("sm")]:
            {
                fontSize:'0.9rem',
                marginRight:'0',
            }
        },   
    },
    palettes:
    {
        boxSizing:"border-box",
        width:"100%",
        display:"grid",
        gridTemplateColumns:"repeat(3,30%)",
        gridGap:"2rem",
        [sizes.down("sm")]:
        {
            gridTemplateColumns:"repeat(2,50%)",
        },
        marginBottom:"2vh"
    },
    title:
    {
        [sizes.down("sm")]:
        {
            fontSize:'1.8rem',
        }
    }
}